name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install system libraries
        run: sudo apt-get update && sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev libavfilter-dev libclang-dev

      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --all-features --release --verbose
      - name: Run tests
        run: cargo test --all-features --release --verbose
